USE master;
GO

IF EXISTS(SELECT * FROM sys.databases WHERE NAME = 'Coddit')
	DROP DATABASE [Coddit];

CREATE DATABASE [Coddit];
GO

USE [Coddit];

CREATE TABLE [Users] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[Email] VARCHAR(100) UNIQUE NOT NULL,
	[Username] VARCHAR(50) UNIQUE NOT NULL,
	[Password] VARCHAR(100) NOT NULL,
    [Salt] VARCHAR(16) NOT NULL,
	[BirthDate] DATE NOT NULL,
	[Picture] VARBINARY(MAX) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[CreatedAt] DATE NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE [Forums] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[Title] VARCHAR(50) UNIQUE NOT NULL,
    [Description] VARCHAR(150) NOT NULL,
	[CreatedAt] DATE NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE [Posts] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [UserID] BIGINT REFERENCES Users(ID) NOT NULL,
    [ForumID] BIGINT REFERENCES Forums(ID) NOT NULL,
    [Title] VARCHAR(50) NOT NULL,
    [Message] VARCHAR(255) NOT NULL,
    [Attachment] VARBINARY(MAX) NULL,
	[CreatedAt] DATE NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE [Comments] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [UserID] BIGINT REFERENCES Users(ID) NOT NULL,
    [PostID] BIGINT REFERENCES Posts(ID) NULL,
	[CommentID] BIGINT REFERENCES Comments(ID) NULL,
    [Message] VARCHAR(255) NOT NULL,
	[CreatedAt] DATE NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE [Vote] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [UserID] BIGINT REFERENCES Users(ID) NOT NULL,
    [PostID] BIGINT REFERENCES Posts(ID) NULL,
	[CommentID] BIGINT REFERENCES Comments(ID) NULL,
    [Value] BIT NOT NULL
);
GO

CREATE TABLE [Roles] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [ForumID] BIGINT REFERENCES Forums(ID) NOT NULL,
    [Title] VARCHAR(50) NOT NULL,
    [IsOwner] BIT NOT NULL DEFAULT 0,
    [IsDefault] BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE [Permissions] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[Title] VARCHAR(50) UNIQUE NOT NULL,
);
GO

CREATE TABLE [HasPermission] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [RoleID] BIGINT REFERENCES Roles(ID) NOT NULL,
    [PermissionID] BIGINT REFERENCES Permissions(ID) NOT NULL,
    [Has] BIT NOT NULL
);
GO

CREATE TABLE [Members] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
    [UserID] BIGINT REFERENCES Users(ID) NOT NULL,
    [ForumID] BIGINT REFERENCES Forums(ID) NOT NULL,
    [RoleID] BIGINT REFERENCES Roles(ID) NOT NULL
);
GO